import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Banner from "./../components/Banner";

export default function Home() {
  const handleOnButtonClick = () => {
    console.log("Clicked");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner onClick={handleOnButtonClick} buttonText="Find coffee stores" />
        <div className={styles.heroImage}>
          <Image
            src="/images/hero-image.png"
            width={700}
            height={400}
            alt="hero"
          />
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
